In [ ]:

import tensorflow as tf
from keras.preprocessing.image import ImageDataGenerator
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from numpy import array

In [ ]:
dataset= pd.read_csv('data.csv')

In [ ]:
dataset

filename  chroma_stft      rmse  ...    mfcc19    mfcc20  label
0       bee.000954.wav     0.629595  0.001046  ...  2.709668  8.512812    bee
1       bee.000484.wav     0.539051  0.001210  ...  2.844197  6.357111    bee
2       bee.001006.wav     0.562158  0.014232  ...  1.001005  6.645530    bee
3       bee.000936.wav     0.608606  0.001223  ...  3.095170  6.855744    bee
4       bee.000468.wav     0.603719  0.001100  ...  2.517323  5.668016    bee
...                ...          ...       ...  ...       ...       ...    ...
4065  nobee.002331.wav     0.509332  0.004819  ...  0.004284  5.220933  nobee
4066  nobee.000757.wav     0.571468  0.004503  ...  3.717404  6.236328  nobee
4067  nobee.002081.wav     0.578200  0.005151  ... -0.368056  5.430214  nobee
4068  nobee.002436.wav     0.624897  0.003145  ... -0.409538  3.908302  nobee
4069  nobee.000200.wav     0.578484  0.004983  ...  0.062567  4.482868  nobee

[4070 rows x 28 columns]

In [ ]:
dataset['label']

0         bee
1         bee
2         bee
3         bee
4         bee
        ...  
4065    nobee
4066    nobee
4067    nobee
4068    nobee
4069    nobee
Name: label, Length: 4070, dtype: object

In [ ]:
from sklearn import preprocessing
levelencoder= preprocessing.LabelEncoder()
dataset['label']= levelencoder.fit_transform(dataset['label'])

In [ ]:
m = dataset.iloc[:, 1:].values

In [ ]:
m


array([[ 6.29595459e-01,  1.04646140e-03,  2.96618737e+03, ...,
         2.70966792e+00,  8.51281166e+00,  0.00000000e+00],
       [ 5.39050758e-01,  1.21033902e-03,  2.51992749e+03, ...,
         2.84419656e+00,  6.35711050e+00,  0.00000000e+00],
       [ 5.62157750e-01,  1.42315626e-02,  2.85111988e+03, ...,
         1.00100529e+00,  6.64553022e+00,  0.00000000e+00],
       ...,
       [ 5.78199506e-01,  5.15128998e-03,  1.67560665e+03, ...,
        -3.68056327e-01,  5.43021441e+00,  1.00000000e+00],
       [ 6.24897182e-01,  3.14479205e-03,  1.70603933e+03, ...,
        -4.09537643e-01,  3.90830231e+00,  1.00000000e+00],
       [ 5.78484118e-01,  4.98281699e-03,  1.74750027e+03, ...,
         6.25668094e-02,  4.48286819e+00,  1.00000000e+00]])

In [ ]:
def split_sequences(sequences, n_steps):
	a, b = list(), list()
	for i in range(len(sequences)):
		# find the end of this pattern
		end_ix = i + n_steps
    
		# check if we are beyond the dataset
		if end_ix > len(sequences):
			break
		# gather input and output parts of the pattern
		seq_x, seq_y = sequences[i:end_ix, :-1], sequences[end_ix-1, -1]
    
		a.append(seq_x)
		b.append(seq_y)
	return array(a), array(b)

In [ ]:
d=dataset[1:26:-1]

In [ ]:
m.shape

(4070, 27)

In [ ]:
m

array([[ 6.29595459e-01,  1.04646140e-03,  2.96618737e+03, ...,
         2.70966792e+00,  8.51281166e+00,  0.00000000e+00],
       [ 5.39050758e-01,  1.21033902e-03,  2.51992749e+03, ...,
         2.84419656e+00,  6.35711050e+00,  0.00000000e+00],
       [ 5.62157750e-01,  1.42315626e-02,  2.85111988e+03, ...,
         1.00100529e+00,  6.64553022e+00,  0.00000000e+00],
       ...,
       [ 5.78199506e-01,  5.15128998e-03,  1.67560665e+03, ...,
        -3.68056327e-01,  5.43021441e+00,  1.00000000e+00],
       [ 6.24897182e-01,  3.14479205e-03,  1.70603933e+03, ...,
        -4.09537643e-01,  3.90830231e+00,  1.00000000e+00],
       [ 5.78484118e-01,  4.98281699e-03,  1.74750027e+03, ...,
         6.25668094e-02,  4.48286819e+00,  1.00000000e+00]])

In [ ]:
a,b = split_sequences(m, 27)

In [ ]:
b

array([0., 0., 0., ..., 1., 1., 1.])

In [ ]:
a

array([[[ 6.29595459e-01,  1.04646140e-03,  2.96618737e+03, ...,
          7.35334873e+00,  2.70966792e+00,  8.51281166e+00],
        [ 5.39050758e-01,  1.21033902e-03,  2.51992749e+03, ...,
          8.10223770e+00,  2.84419656e+00,  6.35711050e+00],
        [ 5.62157750e-01,  1.42315626e-02,  2.85111988e+03, ...,
          4.66146374e+00,  1.00100529e+00,  6.64553022e+00],
        ...,
        [ 5.52716374e-01,  8.67123425e-04,  2.94183280e+03, ...,
          5.52934217e+00,  9.01236176e-01,  7.84008646e+00],
        [ 5.44274211e-01,  1.06035813e-03,  2.61144636e+03, ...,
          6.27785254e+00,  1.77195811e+00,  5.18353224e+00],
        [ 5.87314427e-01,  1.13051280e-03,  2.54816395e+03, ...,
          6.89436150e+00,  7.32693315e-01,  4.08180952e+00]],

       [[ 5.39050758e-01,  1.21033902e-03,  2.51992749e+03, ...,
          8.10223770e+00,  2.84419656e+00,  6.35711050e+00],
        [ 5.62157750e-01,  1.42315626e-02,  2.85111988e+03, ...,
          4.66146374e+00,  1.00100529e

In [ ]:
from sklearn.model_selection import train_test_split
a_train, a_test, b_train, b_test = train_test_split(a, b, test_size = 0.2, random_state = 1)

In [ ]:
n_features = a.shape[2]

In [ ]:
from numpy import array
from numpy import hstack
from keras.models import Sequential
from keras.layers import Dense,Dropout, LSTM
import tensorflow as tf

In [ ]:
model = Sequential()
model.add(LSTM(128, activation='relu', input_shape=(a_train.shape[1:]), return_sequences=True))
model.add(Dropout(0.2))

model.add(LSTM(128, activation='relu'))
model.add(Dropout(0.2))

model.add(Dense(32, activation='relu'))
model.add(Dropout(0.2))

model.add(Dense(1, activation='sigmoid'))

opt = tf.keras.optimizers.Adam(learning_rate=1e-3, decay =  1e-5)
model.compile(loss= 'mse' ,optimizer=opt, metrics=['accuracy'])




#model.compile(optimizer='adam', loss='sparse_categorical_cr',metrics = ['accuracy'])
# fit model
model.fit(a_train, b_train, batch_size=128, epochs=1000, validation_data=(a_test, b_test), verbose=0)


In [ ]:
test_loss, test_acc = model.evaluate(a_test,b_test)
print('test_acc: ',test_acc)

26/26 [==============================] - 0s 17ms/step - loss: 0.2719 - accuracy: 0.7281
test_acc:  0.7280593514442444
